### ISSUE TITLE
Create "Prepare" command

### ISSUE THREAD

**Issue by TheBrockEllis** [TheBrockEllis/ZText#12]
We need a command that takes an item from your inventory and "prepares" it to be used against the zombies. 

The thought is that you "grab" and item to place it in your inventory. That command should update the items array to mark that item as discovered. Then, you can either "set" it in a defensive location or "prepare" it to be used.

"prepare" should remove it from your inventory, put it back into the house[survivor.location].items array

**Comment by allknowingfrog** [comment]
I'm not sure I understand how this differs from the "set" command. Does "prepare" change the state of an item? Like cranking the chainsaw?

**Comment by TheBrockEllis** [comment]
When being attacked, we want to make sure only the items the survivor interacts with are used in the defense. When you "grab" an item, we need to mark that item as "discovered" in the items.js array. This will tell us which items can be used to fight the zombies.

However, once you "grab" an item, there is no easy way to get it out of your inventory. Right now, you can "set" the item next to a defensive position (windows, doors, etc) and I'd imagine that we should add some type of bonus to whatever weapon is in that spot. But if I grab a knife from the kitchen but want to use it in the bathroom when Im attacked, there is no way to do that currently.

The "prepare" command should remove the item  from your inventory and place that item back into the house[survivor.location].items array. But because it's already been "grabbed", discovered should be set = 1 in the items.js array so that when you're attacked we can use it's score against the hoarde of zombies.

Does that make sense? Entirely possible that I could be just completely crazy.

**Comment by allknowingfrog** [comment]
You can already "grab" an item in one room and "set" it in another to use it defensively. Will using "prepare" give a different bonus?

I don't actually understand what "discovered" is supposed to represent. Just that you grabbed the item at some point? Because "look" already reveals everything. Will you have to search rooms in the future?

**Comment by TheBrockEllis** [comment]
Well, I think the point of "prepare()" is that we dont want all of the items that are in the room to be counted toward fighting the zombie. We actually want the survivor to interact with the items before they can be used in the attack.

I just committed some code with the prepare command. I think it works alright. We're almost at the point where we need to start looking at the "game flow". Is it too difficult? It is too repetitive?
