### ISSUE TITLE
Randomize Location of Items

### ISSUE THREAD

**Issue by TheBrockEllis** [TheBrockEllis/ZText#2]
All item placement needs to be randomized. This will increase game replay-ability and make it so that even the game makers need to FIGHT TO SURVIVE!

**Comment by TheBrockEllis** [comment]
@allknowingfrog if you get time, this would be an awesome enhancement. It would make the game an actual game where we would have to really TRY instead of just memorizing item locations.

**Comment by allknowingfrog** [comment]
I'll see what I can come up with.

**Comment by allknowingfrog** [comment]
Done. :)
